"use client";
import { useState } from "react";
import { Check, ChevronRight, Hash, RefreshCw, Save } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { topics } from "@/data/mock";
import type { Draft } from "@/lib/types";

export default function CreatorPage(){
 const [selected,setSelected]=useState(0); const [draft,setDraft]=useState<Draft>({...topics[0].draft}); const [saved,setSaved]=useState(false); const [tab,setTab]=useState<"topics"|"copy"|"cover">("copy");
 const choose=(i:number)=>{setSelected(i);setDraft({...topics[i].draft});setTab("copy")};
 return <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7 lg:px-10"><PageHeader eyebrow="AI-assisted editorial desk" title="Content Creator" description="从十个高匹配选题中挑选方向，再与你的 Writer Agent 一起完成内容。"/>
 <div className="mt-6 flex gap-2 rounded-2xl bg-white/60 p-1.5 lg:hidden">{[["topics","选题"],["copy","文案"],["cover","封面"]].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`flex-1 rounded-xl py-2 text-sm ${tab===id?"bg-[var(--ink)] text-white":""}`}>{label}</button>)}</div>
 <div className="mt-6 grid min-h-[680px] gap-4 lg:grid-cols-[290px_minmax(360px,1fr)_320px]">
  <section className={`${tab!=="topics"?"hidden lg:block":""} panel max-h-[760px] overflow-y-auto p-4`}><div className="flex items-center justify-between px-2 py-2"><h2 className="font-bold">选题候选</h2><span className="text-xs text-[var(--muted)]">10 ideas</span></div><div className="mt-2 space-y-2">{topics.map((t,i)=><button key={t.id} onClick={()=>choose(i)} aria-label={`${t.label}：${t.title}`} className={`w-full rounded-2xl border p-4 text-left transition ${selected===i?"border-[var(--rose-deep)] bg-[var(--rose)]/25":"border-transparent bg-[var(--cream)] hover:border-[var(--line)]"}`}><div className="flex justify-between text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]"><span>{t.label}</span><span>{t.match}% 匹配</span></div><div className="mt-2 flex items-center justify-between gap-2"><p className="text-sm font-semibold">{t.title}</p><ChevronRight size={15}/></div></button>)}</div></section>
  <section className={`${tab!=="copy"?"hidden lg:block":""} panel flex flex-col p-5 sm:p-7`}><div className="flex items-center justify-between"><div><p className="fine">Writer Agent</p><h2 className="mt-1 text-xl font-bold">文案编辑器</h2></div><button className="soft-button flex items-center gap-2 text-sm" onClick={()=>setDraft({...topics[selected].draft,title:topics[selected].draft.title+" ✦"})}><RefreshCw size={15}/>重新生成</button></div><label className="mt-7 text-xs font-bold text-[var(--muted)]">标题<input aria-label="标题" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="mt-2 w-full border-b border-[var(--line)] bg-transparent pb-4 text-2xl font-bold outline-none"/></label><label className="mt-6 flex flex-1 flex-col text-xs font-bold text-[var(--muted)]">正文<textarea aria-label="正文" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} className="mt-2 min-h-[300px] flex-1 resize-none rounded-2xl bg-[var(--cream)] p-5 text-sm font-normal leading-7 text-[var(--ink)] outline-none"/></label><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2"><Hash size={15}/>{draft.tags.map(t=><span key={t} className="rounded-full bg-[var(--almond)] px-3 py-1 text-xs">{t}</span>)}</div><span className="text-xs text-[var(--muted)]">{draft.body.length} 字</span></div></section>
  <aside className={`${tab!=="cover"?"hidden lg:flex":""} panel flex-col p-5`}><div className="flex items-center justify-between"><h2 className="font-bold">封面预览</h2><span className="fine">3:4</span></div><div className="visual-art mt-5 aspect-[3/4] rounded-[24px]" style={{"--art-a":draft.coverColors[0],"--art-b":draft.coverColors[1],"--art-c":draft.coverColors[2]} as React.CSSProperties}><div className="absolute inset-x-5 bottom-5 z-10 rounded-2xl bg-white/78 p-4 backdrop-blur-md"><p className="fine">Autumn look</p><p className="mt-1 font-bold leading-tight">{topics[selected].title}</p></div></div><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1600)}} className="primary-button mt-5 flex items-center justify-center gap-2">{saved?<><Check size={16}/>已保存</>:<><Save size={16}/>保存草稿</>}</button></aside>
 </div></main>
}
