"use client";
import { useState } from "react";
import { Check, Expand } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { PromptCard, type PromptSettings } from "@/components/prompt-card";
import { coverCandidates } from "@/data/mock";

export default function VisualStudioPage(){
 const [prompt,setPrompt]=useState("韩系秋季街拍，奶油色针织与低饱和背景，自然光，松弛但精致的杂志封面构图，保留标题留白。"); const [settings,setSettings]=useState<PromptSettings>({ratio:"3:4",tone:"奶油",composition:"街拍"}); const [selected,setSelected]=useState("cover-1"); const [generating,setGenerating]=useState(false);const [setDone,setSetDone]=useState(false);
 const generate=()=>{setGenerating(true);setTimeout(()=>{setGenerating(false);setSelected("cover-3")},900)};
 return <main className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><PageHeader eyebrow="AI Visual Direction" title="Visual Studio" description="把主题转化为清晰的封面方向，在四个候选中选出最符合个人风格的一张。"/><div className="mt-8 grid gap-5 lg:grid-cols-[360px_1fr]"><PromptCard value={prompt} onChange={setPrompt} settings={settings} onSettingsChange={setSettings} onGenerate={generate} generating={generating}/><section className="panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="fine">4 candidates</p><h2 className="mt-1 text-xl font-bold">封面候选</h2></div><button onClick={()=>{setSetDone(true);setTimeout(()=>setSetDone(false),1400)}} className="soft-button flex items-center gap-2 text-sm">{setDone?<><Check size={15}/>已设为封面</>:"设为封面"}</button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:gap-4">{generating?[0,1,2,3].map(i=><div data-testid="cover-skeleton" key={i} className="aspect-[3/4] animate-pulse rounded-[22px] bg-[var(--almond)]"/>):coverCandidates.map((c,i)=><button key={c.id} aria-label={c.alt} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)} className={`relative overflow-hidden rounded-[22px] border-2 text-left transition ${selected===c.id?"border-[var(--rose-deep)] p-1":"border-transparent"}`}><div className="visual-art aspect-[3/4] rounded-[18px]" style={{"--art-a":c.colors[0],"--art-b":c.colors[1],"--art-c":c.colors[2]} as React.CSSProperties}><span className="absolute bottom-3 left-3 z-10 rounded-full bg-white/80 px-3 py-1.5 text-[10px] font-bold backdrop-blur">{c.composition}</span>{selected===c.id&&<span className="absolute right-3 top-3 z-10 grid h-8 w-8 place-items-center rounded-full bg-[var(--ink)] text-white"><Check size={15}/></span>}<Expand className="absolute bottom-3 right-3 z-10 text-white" size={16}/></div></button>)}</div></section></div></main>
}
