export type AgentStatus = "working" | "ready" | "waiting";
export type WorkflowStatus = "completed" | "running" | "waiting";
export type Agent = { id: string; name: string; role: string; status: AgentStatus; detail?: string; icon: "search" | "sparkles" | "pen" | "shield" };
export type LibraryCategory = "小红书爆款案例库" | "个人审美风格库" | "爆款标题模板库" | "AI图片库";
export type LibraryItem = {
  id: string;
  title: string;
  category: LibraryCategory;
  tags: string[];
  score: number;
  saved: boolean;
  aspect: "portrait" | "square" | "tall";
  colors: [string, string, string];
  description: string;
};
export type WorkflowStep = { id: string; name: string; subtitle: string; status: WorkflowStatus; model?: string; output?: string; duration?: string };
export type EditableDraft = { title: string; body: string; tags: string[]; coverColors: [string, string, string] };
export type DraftPublishStatus = "draft" | "reviewing" | "ready" | "published";
export type Draft = {
  id: string;
  title: string;
  content: string;
  tags: string[];
  coverImage: string;
  images: string[];
  imageSource: "generated" | "library" | "upload" | "none";
  model: string;
  status: "draft";
  publishStatus: DraftPublishStatus;
  platform: "xiaohongshu";
  createdAt: string;
};
export type Topic = { id: string; label: string; title: string; match: number; tags: string[]; draft: EditableDraft };
export type CoverCandidate = { id: string; alt: string; composition: string; colors: [string, string, string] };
export type ModelProvider = "local-cli" | "cloud-api" | "openai" | "mock";
export type ModelConfig = { id: string; kind: "text" | "image"; name: string; provider: ModelProvider; mode: "cloud" | "local-cli" | "image"; status: "connected" | "disconnected" };
export type ContentGoal = "涨粉" | "种草" | "品牌推广";
export type ContentTask = { topic: string; audiences: string[]; styles: string[]; goal: ContentGoal; useIntelligence: boolean };
export type TitleCandidate = { id: string; title: string; match: number };
export type SafetyCheck = { id: string; label: string; status: "passed" | "review" };
export type CopyingRisk = {
  status: "passed" | "review";
  titleExactMatch: boolean;
  titleHighSimilarity: boolean;
  bodyLongOverlap: boolean;
  regenerated: boolean;
  warning?: string;
};
export type SafetyReport = { score: number; checks: SafetyCheck[]; copyingRisk: CopyingRisk };
